### ISSUE TITLE
Question to the implementation of FLEX-VFL

### ISSUE THREAD

**Issue by hzhou10cs** [rpi-nsl/flex-vfl#1]
Hi! I am so glad that you have posted the code of Flex-VFL and I appreciate so much for this work.

I noticed that the multimodal dataset uses some special models and training strategies, such as CPC, and MMILB. I found that these techniques are originally proposed in the paper "Improving Multimodal Fusion with Hierarchical Mutual Information Maximization for Multimodal Sentiment Analysis", but not mentioned in the whole paper of the Flex-VFL. My question is: are they also applied in the Flex-VFL by default? Or is there any pure version of Flex-VFL not posted yet?

**Comment by timcast725** [comment]
I believe the results in the Flex-VFL paper do use CPC and MMILB for all the baselines as part of the server model loss calculation. I forgot to mention this in the paper itself. When running the code, using the flag "--contrast" will turn on these additions to the loss (see example in run_slurm.sh). If you want the more "pure" Flex-VFL without CPC and MMILB, you can leave out this flag. It would be interesting to see how each VFL algorithm performs without CPC and MMILB. 

I will close the issue, but feel free to email me if you have more questions!
